### ISSUE TITLE
你好，双显示器有卡顿么？

### ISSUE THREAD

**Issue by yunWJR** [Hyejeongdd/NUC8i5BEK-Hackintosh#10]
你好，我用的一台4K、一台2K（type-c 转 HDMI），感觉比接一台4K 卡顿，你有卡顿么？

**Comment by Hyejeongdd** [comment]
Hi, 麻烦提供一下使用场景，目前我多浏览器使用下感觉良好

**Comment by Hyejeongdd** [comment]
> 你好，我用的一台4K、一台2K（type-c 转 HDMI），感觉比接一台4K 卡顿，你有卡顿么？

Hi, 麻烦提供一下使用场景，目前我多浏览器使用下感觉良好
