### ISSUE TITLE
macos 12 分支，安装 12 后会卡死的解决方案。

### ISSUE THREAD

**Issue by hmilyfyj** [Hyejeongdd/NUC8i5BEK-Hackintosh#11]
我在论坛里看到是因为使用了 FakePCIID，先禁用掉就正常了。

**Comment by Hyejeongdd** [comment]
> 我在论坛里看到是因为使用了 FakePCIID，先禁用掉就正常了。

可以提供下 logs 吗

**Comment by hmilyfyj** [comment]
请问是哪个 logs？

你使用一切正常吗？正常的话就不用麻烦排查了，因为我目前使用也正常。本来是想给你提供思路的，如果你也正常使用那就太好了。

很久以前就开始用你提供的 efi，很稳定，非常感谢。
