### ISSUE TITLE
求助：设置了三码之后，可以登录 iCloud 和 AppStore，但是无法使用 iMessage 和 Facetime

### ISSUE THREAD

**Issue by lkxed** [Hyejeongdd/NUC8i5BEK-Hackintosh#2]
您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
<img width="420" alt="Snipaste_2020-08-29_16-33-47" src="https://user-images.githubusercontent.com/39257389/91632750-7cf70e00-ea15-11ea-8132-9af25a2425c5.png">
希望能够得到一些帮助，谢谢🙏！

**Comment by Hyejeongdd** [comment]
> 您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
> <img alt="Snipaste_2020-08-29_16-33-47" width="420" src="https://user-images.githubusercontent.com/39257389/91632750-7cf70e00-ea15-11ea-8132-9af25a2425c5.png">
> 希望能够得到一些帮助，谢谢🙏！

收到了你的issue,我希望能看到关于OCC下的三码页面。期待你的回复

**Comment by lkxed** [comment]
> > 您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
> > <img alt="Snipaste_2020-08-29_16-33-47" width="420" src="https://user-images.githubusercontent.com/39257389/91632750-7cf70e00-ea15-11ea-8132-9af25a2425c5.png">
> > 希望能够得到一些帮助，谢谢🙏！
> 
> 收到了你的issue,我希望能看到关于OCC下的三码页面。期待你的回复

你好，这是我的 OCC 三码页面：
<img width="974" alt="Snipaste_2020-08-29_16-45-50" src="https://user-images.githubusercontent.com/39257389/91632965-386c7200-ea17-11ea-9336-00663a27bd12.png">

**Comment by Hyejeongdd** [comment]
> > > 您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
> > > <img alt="Snipaste_2020-08-29_16-33-47" width="420" src="https://user-images.githubusercontent.com/39257389/91632750-7cf70e00-ea15-11ea-8132-9af25a2425c5.png">
> > > 希望能够得到一些帮助，谢谢🙏！
> > 
> > 
> > 收到了你的issue,我希望能看到关于OCC下的三码页面。期待你的回复
> 
> 你好，这是我的 OCC 三码页面：
> <img alt="Snipaste_2020-08-29_16-45-50" width="974" src="https://user-images.githubusercontent.com/39257389/91632965-386c7200-ea17-11ea-9336-00663a27bd12.png">

System Serial Number = C07DF0GXJYVX 系统无法获得该型号的设备信息，说明该序列号并不存在。

我的建议是重新生成一次System Serial Number，与此同时，您的System UUID 和 ROM也需要重新生成。

期待您的后续回复

**Comment by lkxed** [comment]
> > > > 您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
> > > > <img alt="Snipaste_2020-08-29_16-33-47" width="420" src="https://user-images.githubusercontent.com/39257389/91632750-7cf70e00-ea15-11ea-8132-9af25a2425c5.png">
> > > > 希望能够得到一些帮助，谢谢🙏！
> > > 
> > > 
> > > 收到了你的issue,我希望能看到关于OCC下的三码页面。期待你的回复
> > 
> > 
> > 你好，这是我的 OCC 三码页面：
> > <img alt="Snipaste_2020-08-29_16-45-50" width="974" src="https://user-images.githubusercontent.com/39257389/91632965-386c7200-ea17-11ea-9336-00663a27bd12.png">
> 
> System Serial Number = C07DF0GXJYVX 系统无法获得该型号的设备信息，说明该序列号并不存在。
> 
> 我的建议是重新生成一次System Serial Number，与此同时，您的System UUID 和 ROM也需要重新生成。
> 
> 期待您的后续回复

您好，“System Serial Number = C07DF0GXJYVX 系统无法获得该型号的设备信息” 这个提示信息是在哪里可以获取到呢？另外，如果我要更换三码，需要预先执行哪些操作，例如退出 iCloud 登录、在 Apple ID 中删除设备？

**Comment by Hyejeongdd** [comment]
> > > > > 您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
> > > > > <img alt="Snipaste_2020-08-29_16-33-47" width="420" src="https://user-images.githubusercontent.com/39257389/91632750-7cf70e00-ea15-11ea-8132-9af25a2425c5.png">
> > > > > 希望能够得到一些帮助，谢谢🙏！
> > > > 
> > > > 
> > > > 收到了你的issue,我希望能看到关于OCC下的三码页面。期待你的回复
> > > 
> > > 
> > > 你好，这是我的 OCC 三码页面：
> > > <img alt="Snipaste_2020-08-29_16-45-50" width="974" src="https://user-images.githubusercontent.com/39257389/91632965-386c7200-ea17-11ea-9336-00663a27bd12.png">
> > 
> > 
> > System Serial Number = C07DF0GXJYVX 系统无法获得该型号的设备信息，说明该序列号并不存在。
> > 我的建议是重新生成一次System Serial Number，与此同时，您的System UUID 和 ROM也需要重新生成。
> > 期待您的后续回复
> 
> 您好，“System Serial Number = C07DF0GXJYVX 系统无法获得该型号的设备信息” 这个提示信息是在哪里可以获取到呢？另外，如果我要更换三码，需要预先执行哪些操作，例如退出 iCloud 登录、在 Apple ID 中删除设备？

https://checkcoverage.apple.com/hk/zh/ 在这里您可以查询到序列号System Serial Number的详细信息。

您可以退出Apple ID 以及一些Apple ID 关联的服务再进行更换三码的操作。

**Comment by lkxed** [comment]
你好，我重新更换了三码，我现在的序列号是 C07XR3Z7JYVX，官网查询是无效的，依旧是 AppStore 和 iCloud 可登录，但 iMessage 和 Facetime 不可登录，显示“认证过程中出错”：
<img width="649" alt="Snipaste_2020-08-29_18-11-33" src="https://user-images.githubusercontent.com/39257389/91634592-057cab00-ea24-11ea-9c20-2ac72dd3c8c5.png">
我在网络上查询资料，有几篇说这个问题与 NVRAM 有关，”NVRAM通常以一块芯片的形式存在，所以系统是否支持NVRAM，取决于主板。NVRAM在黑苹果中有及其重要的作用，第一，是用于重启后保存与蓝牙、屏幕亮度、系统音量、**iMessage**、**FaceTime**等相关参数；“ [参考链接](https://heipg.cn/tutorial/what-is-nvram.html)，您认为 NVRAM 是否与我的问题有关？另外，我在 bilibili 上也看到一些朋友遇到与我相同的问题。

**Comment by Hyejeongdd** [comment]
> 你好，我重新更换了三码，我现在的序列号是 C07XR3Z7JYVX，官网查询是无效的，依旧是 AppStore 和 iCloud 可登录，但 iMessage 和 Facetime 不可登录，显示“认证过程中出错”：
> <img alt="Snipaste_2020-08-29_18-11-33" width="649" src="https://user-images.githubusercontent.com/39257389/91634592-057cab00-ea24-11ea-9c20-2ac72dd3c8c5.png">
> 我在网络上查询资料，有几篇说这个问题与 NVRAM 有关，”NVRAM通常以一块芯片的形式存在，所以系统是否支持NVRAM，取决于主板。NVRAM在黑苹果中有及其重要的作用，第一，是用于重启后保存与蓝牙、屏幕亮度、系统音量、**iMessage**、**FaceTime**等相关参数；“ [参考链接](https://heipg.cn/tutorial/what-is-nvram.html)，您认为 NVRAM 是否与我的问题有关？另外，我在 bilibili 上也看到一些朋友遇到与我相同的问题。

我觉得和NVRAM关系不大，当然你可以在更换System Serial Number后Reset NVRAM一次，我个人更建议摇号到可以在官网查询到序列号吗

期待您的反馈

**Comment by lkxed** [comment]
> > 你好，我重新更换了三码，我现在的序列号是 C07XR3Z7JYVX，官网查询是无效的，依旧是 AppStore 和 iCloud 可登录，但 iMessage 和 Facetime 不可登录，显示“认证过程中出错”：
> > <img alt="Snipaste_2020-08-29_18-11-33" width="649" src="https://user-images.githubusercontent.com/39257389/91634592-057cab00-ea24-11ea-9c20-2ac72dd3c8c5.png">
> > 我在网络上查询资料，有几篇说这个问题与 NVRAM 有关，”NVRAM通常以一块芯片的形式存在，所以系统是否支持NVRAM，取决于主板。NVRAM在黑苹果中有及其重要的作用，第一，是用于重启后保存与蓝牙、屏幕亮度、系统音量、**iMessage**、**FaceTime**等相关参数；“ [参考链接](https://heipg.cn/tutorial/what-is-nvram.html)，您认为 NVRAM 是否与我的问题有关？另外，我在 bilibili 上也看到一些朋友遇到与我相同的问题。
> 
> 我觉得和NVRAM关系不大，当然你可以在更换System Serial Number后Reset NVRAM一次，我个人更建议摇号到可以在官网查询到序列号吗
> 
> 期待您的反馈

您好，您的意思是否是序列号需要在官网可以查询到才可以？我在网络上看的教程说，可以在官网查询到说明已经被人使用了，所以需要查询显示无效才可以使用，是否是我理解上有问题呢？

**Comment by Hyejeongdd** [comment]
> > > 你好，我重新更换了三码，我现在的序列号是 C07XR3Z7JYVX，官网查询是无效的，依旧是 AppStore 和 iCloud 可登录，但 iMessage 和 Facetime 不可登录，显示“认证过程中出错”：
> > > <img alt="Snipaste_2020-08-29_18-11-33" width="649" src="https://user-images.githubusercontent.com/39257389/91634592-057cab00-ea24-11ea-9c20-2ac72dd3c8c5.png">
> > > 我在网络上查询资料，有几篇说这个问题与 NVRAM 有关，”NVRAM通常以一块芯片的形式存在，所以系统是否支持NVRAM，取决于主板。NVRAM在黑苹果中有及其重要的作用，第一，是用于重启后保存与蓝牙、屏幕亮度、系统音量、**iMessage**、**FaceTime**等相关参数；“ [参考链接](https://heipg.cn/tutorial/what-is-nvram.html)，您认为 NVRAM 是否与我的问题有关？另外，我在 bilibili 上也看到一些朋友遇到与我相同的问题。
> > 
> > 
> > 我觉得和NVRAM关系不大，当然你可以在更换System Serial Number后Reset NVRAM一次，我个人更建议摇号到可以在官网查询到序列号吗
> > 期待您的反馈
> 
> 您好，您的意思是否是序列号需要在官网可以查询到才可以？我在网络上看的教程说，可以在官网查询到说明已经被人使用了，所以需要查询显示无效才可以使用，是否是我理解上有问题呢？

我也看过类似的说法，更多的资料告诉我在认证iMessage和FaceTime上是根据MLB和ROM进行工作的。

同时建议您勾选上SpoofVendor

期待您的进一步尝试

**Comment by maileha** [comment]
其实这两个功能真的不需要去使用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liu Kaixiang <notifications@github.com&gt;
发送时间: 2020年8月29日 16:35
收件人: Hyejeongdd/NUC8i5BEK-Hackintosh <NUC8i5BEK-Hackintosh@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Hyejeongdd/NUC8i5BEK-Hackintosh] 求助：设置了三码之后，可以登录 iCloud 和 AppStore，但是无法使用 iMessage 和 Facetime (#2)





 
您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
 
 希望能够得到一些帮助，谢谢🙏！

**Comment by maileha** [comment]
有空的时候我给你看下，最近有点忙，你把你的config给我



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liu Kaixiang <notifications@github.com&gt;
发送时间: 2020年8月29日 16:35
收件人: Hyejeongdd/NUC8i5BEK-Hackintosh <NUC8i5BEK-Hackintosh@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Hyejeongdd/NUC8i5BEK-Hackintosh] 求助：设置了三码之后，可以登录 iCloud 和 AppStore，但是无法使用 iMessage 和 Facetime (#2)





 
您好，我使用了您的 2020/08/19 的 0.6.1 分支版本的 EFI，安装完进入系统后使用 OCC 随机生成了三码，然后使用 ProperTree 将三码复制进 config.plist 文件中，重启后成功登录 iCloud 和 AppStore，并能够使用 App 下载和隔空投送的功能，唯独 iMessage 和 Facetime 功能不可用，登录 iMessage 的时候的错误提示如下：
 
 希望能够得到一些帮助，谢谢🙏！

**Comment by lkxed** [comment]
您好，这是我的 [config.plist](https://cowtransfer.com/s/113595902cfc48)，我最近比较忙，不再尝试了。使用 iMessage 是希望可以在电脑上接受验证码短信，这样网页登录时不需要去手动输入验证码，虽然验证码只有 6 位输起来并不麻烦。

**Comment by Hyejeongdd** [comment]
> 您好，这是我的 [config.plist](https://cowtransfer.com/s/113595902cfc48)，我最近比较忙，不再尝试了。使用 iMessage 是希望可以在电脑上接受验证码短信，这样网页登录时不需要去手动输入验证码，虽然验证码只有 6 位输起来并不麻烦。

已为您替换了新的三码信息,config.plist将通过邮箱发送给您
