### ISSUE TITLE
系统启动后5~10秒冻结

### ISSUE THREAD

**Issue by 582033** [Hyejeongdd/NUC8i5BEK-Hackintosh#4]
在啰嗦模式下，顺利跑完码并进入系统后，5~10秒系统冻结卡死，需要重启，大概有50%的几率会冻结卡死，这是什么情况呢？

nuc8i5硬改机

**Comment by Hyejeongdd** [comment]
> 在啰嗦模式下，顺利跑完码并进入系统后，5~10秒系统冻结卡死，需要重启，大概有50%的几率会冻结卡死，这是什么情况呢？
> 
> nuc8i5硬改机

目前在我的机器上不会出现您的问题，请发送一下您的硬盘型号，谢谢！

**Comment by 582033** [comment]
因为白果转接卡兼容性导致的oc引导兼容问题；
更换转接卡后解决

**Comment by Hyejeongdd** [comment]
> 因为白果转接卡兼容性导致的oc引导兼容问题；
> 更换转接卡后解决

好的 issue已关闭
