### ISSUE TITLE
0.6.7启动无法找到引导程序

### ISSUE THREAD

**Issue by AaronChun** [Hyejeongdd/NUC8i5BEK-Hackintosh#7]
好像缺bootstrap

**Comment by yqchilde** [comment]
@AaronChun 
周末已翻过车，解决方法：
开机一直按 f2 进入bios，然后退出会关机重启，有了logo去清除nvram，清除了就可以。

**Comment by AaronChun** [comment]
> @AaronChun
> 周末已翻过车，解决方法：
> 开机一直按 f2 进入bios，然后退出会关机重启，有了logo去清除nvram，清除了就可以。

好的，感谢，我试一下

**Comment by AaronChun** [comment]
更新引导后，使用U盘启动，在硬盘选择界面，点击“空格键”，选择清楚NVRAM，0.6.7就可以正常进入系统了
