### ISSUE TITLE
OC  0.6.8  BigSUR  Update  

### ISSUE THREAD

**Issue by enderaltin** [Hyejeongdd/NUC8i5BEK-Hackintosh#8]
Hi, will you update? Nuc8i5BEK ?

**Comment by Hyejeongdd** [comment]
> Hi, will you update? Nuc8i5BEK ?

yep. will update tonight. I have add VirtualSMC new feature and make a test.

**Comment by enderaltin** [comment]
Thank you, I am waiting impatiently

**Comment by Hyejeongdd** [comment]
> Thank you, I am waiting impatiently

Ohhh. I will finish update work as soon as possible.

**Comment by enderaltin** [comment]
ok, wait
